### PR TITLE
Revert "Revert "Bug5696""

### PR DESCRIPTION
**Pull request by kkjeer**
Reverts cliffkoh/office-ui-fabric-react#3

### CODE REVIEW

**Comment by kkjeer** [comment]
@msft-github-bot make sure @cliffkoh approves the pull request

**Comment by kkjeer** [comment]
@msft-github-bot hold this pr for 2 mins

**Comment by kkjeer** [comment]
@msft-github-bot also make sure that are at least five hundred and fifteen approvals

**Comment by kkjeer** [comment]
@msft-github-bot require at least 1 approval

**Review by cliffkoh — APPROVED** [review]

**Pull request merged**
