### PR TITLE
Bug5696

### PR DESCRIPTION
**Pull request by cliffkoh**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #5696
- [x] Include a change request file using `$ npm run change`

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by cliffkoh** [comment]
@msft-github-bot hold this for no longer than 1 minute and make sure @kkjeer approves

**Comment by cliffkoh** [comment]
@msft-github-bot hold this for 1 minute and make sure @kkjeer approves

**Comment by cliffkoh** [comment]
@msft-github-bot keep this open for 1 min and require @kkjeer approval

**Comment by cliffkoh** [comment]
@msft-github-bot require @kkjeer approval and hold this for 1 minute

**Comment by cliffkoh** [comment]
@msft-github-bot require @kkjeer and @cliffkoh approval

**Comment by cliffkoh** [comment]
@msft-github-bot require @cliffkoh to approve and require at least 2 reviewers

**Comment by cliffkoh** [comment]
@msft-github-bot require kkjeer to approve

**Comment by cliffkoh** [comment]
@msft-github-bot require @kkjeer to approve

**Review by kkjeer — APPROVED** [review]

**Comment by cliffkoh** [comment]
@msft-github-bot hold this for 1 minute

**Comment by cliffkoh** [comment]
@msft-github-bot revert to original automerge settings

**Comment by cliffkoh** [comment]
@msft-github-bot hold this pr for 1 minute

**Pull request merged**
